import Head from 'next/head'
import Hero from "../screen/hero/Hero";
import OurUsers from "../screen/ourUsers/OurUsers";

export default function Home() {
  return (
      <div className="layout">
          <Head>
              <title>Test TS Next.js</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          <header/>
          <main>
              <Hero/>
              <OurUsers/>
          </main>
          <footer/>
      </div>
  )
}
